export const equipmentCategories = [
  {
    id: "growing-room",
    title: "1. Growing Room / Farm Infrastructure",
    tags: ["production"],
    items: [
      "PUF/PUF insulated panels",
      "Insulated mushroom growing-room doors",
      "MS/GI mushroom growing racks",
      "Multi-tier racks",
      "Growing shelves",
      "Growing trays",
      "Growing nets",
      "Floor trolleys/carts",
      "Mushroom picking trolley",
      "SS work tables",
      "PVC/food-grade storage bins",
      "Drainage system",
      "Insect-proof doors/nets",
      "Air curtains"
    ]
  },
  {
    id: "hvac",
    title: "2. HVAC & Climate Control",
    tags: ["production", "compost"],
    description: "Commercial mushroom systems commonly integrate cooling, humidification, fresh-air ventilation, exhaust and environmental automation rather than treating these as isolated devices.",
    items: [
      "Air Handling Unit (AHU)",
      "HVAC/cooling system",
      "Refrigeration unit",
      "Chiller",
      "Evaporator coil",
      "Condenser unit",
      "Fresh-air blower",
      "Exhaust fan",
      "Circulation fan",
      "Ventilation ducts",
      "GI/insulated ducting",
      "Motorized dampers",
      "Fresh-air dampers",
      "Heating unit",
      "Electric heater",
      "Steam heating system",
      "Air filters",
      "HEPA filtration where required",
      "Climate-control panel",
      "Automatic temperature controller",
      "Humidity controller",
      "CO₂ controller"
    ]
  },
  {
    id: "humidification",
    title: "3. Humidification / Fogging",
    tags: ["production"],
    items: [
      "High-pressure fogger",
      "Low-pressure fogging system",
      "Ultrasonic humidifier",
      "Centrifugal humidifier",
      "Humidifier pump",
      "High-pressure pump",
      "Fogging nozzles",
      "SS/GI fogging pipeline",
      "Solenoid valves",
      "Automatic humidity control"
    ]
  },
  {
    id: "monitoring",
    title: "4. Temperature / Humidity / CO₂ Monitoring",
    tags: ["production", "compost"],
    items: [
      "Digital thermometer",
      "Digital hygrometer",
      "Temperature sensor",
      "RH sensor",
      "CO₂ sensor",
      "CO₂ meter",
      "Compost temperature probe",
      "Data logger",
      "Multi-parameter environmental sensor",
      "Digital control panel",
      "PLC/HMI control system",
      "Remote monitoring system"
    ]
  },
  {
    id: "water",
    title: "5. Water System",
    tags: ["production", "compost"],
    items: [
      "Borewell/water supply system",
      "Water storage tank",
      "SS water tank",
      "RO/filtration system",
      "Water softener",
      "Pressure pump",
      "Booster pump",
      "Irrigation pump",
      "Fogging pump",
      "Water pipelines",
      "Solenoid valves",
      "Flow meter",
      "Pressure gauge",
      "UV water treatment, where required"
    ]
  },
  {
    id: "compost",
    title: "6. Compost / Substrate Preparation",
    tags: ["compost"],
    description: "Especially important for integrated commercial Button Mushroom projects. Commercial machinery suppliers list compost turners, tunnels, AHUs/blowers, and filling machinery as separate components.",
    items: [
      "Raw-material weighing system",
      "Straw cutter/chopper",
      "Chaff cutter",
      "Substrate mixer",
      "Compost mixer",
      "Bio-compost mixing machine",
      "Compost turner",
      "Conveyor system",
      "Compost filling machine",
      "Compost filler",
      "Compost bunker",
      "Phase-I composting equipment",
      "Phase-II composting equipment",
      "Compost tunnel",
      "Tunnel AHU",
      "Composting blower",
      "Phase-I bunker blower",
      "Phase-II pasteurization blower",
      "Pasteurization tunnel",
      "Pasteurization tunnel doors",
      "Steam generator",
      "Boiler",
      "Steam pipeline",
      "Temperature monitoring system"
    ]
  },
  {
    id: "pasteurization",
    title: "7. Pasteurization / Sterilization",
    tags: ["compost"],
    description: "The appropriate process depends on the mushroom species and substrate; commercial sources distinguish pasteurization from sterilization equipment.",
    items: [
      "Steam boiler",
      "Steam generator",
      "Pasteurization chamber",
      "Pasteurization tunnel",
      "Hot-water pasteurization tank",
      "Atmospheric steamer",
      "Autoclave",
      "Pressure sterilizer",
      "Steam distribution system",
      "Temperature/pressure monitoring",
      "Sterilization racks/carts"
    ]
  },
  {
    id: "spawning",
    title: "8. Spawning / Bag Filling",
    tags: ["compost", "production"],
    items: [
      "Spawning machine",
      "Spawn dosing machine",
      "Spawn mixing machine",
      "Bag filling machine",
      "Substrate bag filler",
      "Bag sealing machine",
      "Impulse heat sealer",
      "Continuous band sealer",
      "Bag perforation machine",
      "Label printer",
      "Batch/lot labelling system"
    ]
  },
  {
    id: "spawn-lab",
    title: "9. Spawn Laboratory",
    tags: ["compost"],
    description: "For an in-house spawn facility. A commercial in-house substrate/spawn operation generally needs clean-air, sterilization, culture, cold storage and traceability systems.",
    items: [
      "Laminar Air Flow cabinet",
      "Biological safety/clean bench as appropriate",
      "Autoclave",
      "Pressure sterilizer",
      "Incubator",
      "Culture racks",
      "Laboratory refrigerator",
      "Laboratory freezer",
      "Hot air oven",
      "Weighing balance",
      "Magnetic stirrer",
      "Microscope",
      "pH meter",
      "BOD/incubation equipment where required",
      "Culture media preparation equipment",
      "Clean-room/controlled workspace equipment"
    ]
  },
  {
    id: "incubation",
    title: "10. Incubation / Spawn Run",
    tags: ["production"],
    items: [
      "Incubation racks",
      "Temperature-control system",
      "Humidity-control system",
      "Air circulation fans",
      "Fresh-air system",
      "CO₂ monitoring",
      "Monitoring sensors",
      "Material-handling carts"
    ]
  },
  {
    id: "casing",
    title: "11. Casing / Button Mushroom Operations",
    tags: ["production"],
    items: [
      "Casing soil mixer",
      "Casing soil preparation unit",
      "Casing pasteurization system",
      "Casing soil filling machine",
      "Casing machine",
      "Casing layer equipment",
      "Casing material storage bins",
      "Casing transport carts"
    ]
  },
  {
    id: "harvesting",
    title: "12. Harvesting",
    tags: ["production"],
    description: "Electric/hydraulic picking trolleys and specialized shelving are used in larger modern mushroom operations.",
    items: [
      "Mushroom picking trolley",
      "Electric picking trolley",
      "Hydraulic picking trolley",
      "Harvesting knife",
      "SS harvesting tools",
      "Food-grade crates",
      "Harvest baskets",
      "Digital weighing scale",
      "Platform scale",
      "Sorting tables"
    ]
  },
  {
    id: "sorting",
    title: "13. Sorting / Grading",
    tags: ["production"],
    items: [
      "Sorting table",
      "Inspection table",
      "Grading conveyor",
      "Conveyor belt",
      "Digital weighing system",
      "Size/grading equipment",
      "Food-grade crates"
    ]
  },
  {
    id: "packing",
    title: "14. Packing Machinery",
    tags: ["production"],
    description: "Commercial mushroom project machinery lists commonly include packaging equipment along with refrigeration and water systems.",
    items: [
      "Mushroom weighing machine",
      "Automatic weighing/filling machine",
      "Punnet filling system",
      "Tray sealing machine",
      "Lidding machine",
      "Flow-wrap packaging machine",
      "Vacuum packing machine",
      "MAP packaging machine",
      "Shrink-wrapping machine",
      "Continuous band sealer",
      "Label printer",
      "Date/batch coding machine",
      "Barcode printer",
      "Checkweigher"
    ]
  },
  {
    id: "cold-storage",
    title: "15. Cold Storage / Post-Harvest",
    tags: ["production"],
    items: [
      "Cold room",
      "Mushroom cold storage",
      "Refrigeration unit",
      "Evaporator",
      "Condenser",
      "Cold-room controller",
      "Temperature data logger",
      "Blast chiller / rapid cooling system",
      "Vacuum refrigerator, where applicable",
      "Cold-room racks",
      "Refrigerated holding area",
      "Cold-chain handling equipment"
    ]
  },
  {
    id: "processing",
    title: "16. Mushroom Drying / Processing",
    tags: ["production"],
    description: "Commercial machinery catalogues also include mushroom dryers alongside growing, cold-room and processing equipment.",
    items: [
      "Mushroom dryer",
      "Tray dryer",
      "Hot-air dryer",
      "Dehydrator",
      "Solar dryer",
      "Slicing machine",
      "Grinding/powdering machine",
      "Pulverizer",
      "Vacuum packing machine",
      "Food-grade storage system"
    ]
  },
  {
    id: "electrical",
    title: "17. Electrical System",
    tags: ["production", "compost"],
    items: [
      "Main electrical panel",
      "MCC panel",
      "APFC panel",
      "Distribution panel",
      "Control panel",
      "PLC panel",
      "VFD",
      "MCB",
      "MCCB",
      "Contactors",
      "Relays",
      "Sensors",
      "Cable trays",
      "Industrial wiring",
      "Earthing system",
      "Surge protection",
      "Automatic voltage protection",
      "DG generator",
      "UPS",
      "Solar power system where applicable"
    ]
  },
  {
    id: "automation",
    title: "18. Automation / Smart Farm Control",
    tags: ["production", "compost"],
    items: [
      "PLC",
      "HMI touchscreen",
      "SCADA",
      "IoT gateway",
      "Remote monitoring",
      "GSM/Wi-Fi controller",
      "Temperature automation",
      "RH automation",
      "CO₂ automation",
      "Fan automation",
      "Fogger automation",
      "HVAC automation",
      "Alarm system",
      "Data logging",
      "Dashboard/control software"
    ]
  },
  {
    id: "cleaning",
    title: "19. Cleaning & Sanitation",
    tags: ["production", "compost"],
    items: [
      "High-pressure washer",
      "Pressure sprayer",
      "Fogging/disinfection machine",
      "Spray pump",
      "Floor scrubber",
      "Foam cleaning system",
      "UV equipment where appropriate",
      "Hand-washing station",
      "Foot-bath/sanitation station",
      "PPE storage",
      "Waste bins",
      "Cleaning tools"
    ]
  },
  {
    id: "material-handling",
    title: "20. Material Handling",
    tags: ["production", "compost"],
    items: [
      "Hand trolley",
      "Platform trolley",
      "Pallet trolley",
      "Forklift",
      "Electric pallet truck",
      "Conveyor",
      "Loading trolley",
      "Storage racks",
      "Pallets",
      "Weighing scales"
    ]
  },
  {
    id: "waste",
    title: "21. Waste Management",
    tags: ["production", "compost"],
    items: [
      "Spent mushroom substrate handling system",
      "Waste conveyor",
      "Organic waste bins",
      "Compost/recycling equipment",
      "Waste storage area",
      "Drainage/effluent-management system"
    ]
  },
  {
    id: "office",
    title: "22. Commercial Farm Office / Control Room",
    tags: ["production", "compost"],
    items: [
      "Control console",
      "Computer",
      "Network equipment",
      "CCTV",
      "NVR",
      "Display monitor",
      "Production dashboard",
      "Inventory software",
      "Batch/lot traceability system",
      "Printer",
      "Barcode/label printer"
    ]
  },
  {
    id: "core-list",
    title: "23. Major Commercial Equipment — Core List",
    tags: ["production", "compost"],
    description: "Essential commercial mushroom farm equipment & machinery for the 3D planner.",
    items: [
      "Mushroom Growing Room",
      "PUF Panels",
      "Insulated Mushroom Door",
      "MS/GI Growing Racks",
      "Mushroom Picking Trolley",
      "HVAC System",
      "Refrigeration Unit",
      "Air Handling Unit (AHU)",
      "Fresh Air Blower",
      "Exhaust Fan",
      "Circulation Fan",
      "GI Air Ducting",
      "Motorized Damper",
      "Humidifier",
      "Fogging System",
      "High Pressure Pump",
      "Temperature Sensor",
      "Humidity Sensor",
      "CO₂ Sensor",
      "Climate Control Panel",
      "PLC Control Panel",
      "Compost Turner",
      "Compost Mixer",
      "Compost Filler",
      "Compost Tunnel",
      "Composting Blower",
      "Phase-I Bunker",
      "Phase-II Pasteurization Tunnel",
      "Pasteurization Blower",
      "Steam Boiler",
      "Steam Generator",
      "Hot Water Pasteurization Tank",
      "Autoclave",
      "Spawning Machine",
      "Spawn Dosing Machine",
      "Bag Filling Machine",
      "Bag Sealing Machine",
      "Substrate Mixer",
      "Laminar Air Flow",
      "Laboratory Autoclave",
      "Incubator",
      "Laboratory Refrigerator",
      "Casing Mixer",
      "Casing Machine",
      "Harvesting Tools",
      "Digital Weighing Scale",
      "Sorting Table",
      "Conveyor",
      "Mushroom Packing Machine",
      "Tray Sealing Machine",
      "Flow-Wrap Machine",
      "Vacuum Packing Machine",
      "MAP Packaging Machine",
      "Labeling Machine",
      "Batch Coding Machine",
      "Cold Room",
      "Blast Chiller",
      "Mushroom Dryer",
      "Drying Chamber",
      "Water Filtration System",
      "RO System",
      "Water Storage Tank",
      "Water Pump",
      "Electrical Distribution Panel",
      "APFC Panel",
      "MCC Panel",
      "DG Generator",
      "UPS",
      "CCTV System",
      "IoT Farm Monitoring",
      "SCADA/HMI",
      "Material Handling Trolley",
      "Forklift",
      "Waste Management System"
    ]
  }
];
